# Generated by Django 5.2.5 on 2025-09-12 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('castmember_app', '0001_initial'),
        ('category_app', '0001_initial'),
        ('genre_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVideoMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('raw_location', models.CharField(max_length=255)),
                ('encoded_location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 1), ('PROCESSING', 2), ('COMPLETED', 3), ('ERROR', 4)], default=1, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('raw_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('launch_year', models.IntegerField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opened', models.BooleanField()),
                ('published', models.BooleanField()),
                ('rating', models.CharField(choices=[('ER', 1), ('L', 2), ('AGE_10', 3), ('AGE_12', 4), ('AGE_14', 5), ('AGE_16', 6), ('AGE_18', 7)], max_length=10)),
                ('banner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_app.imagemedia')),
                ('cast_members', models.ManyToManyField(related_name='videos', to='castmember_app.castmember')),
                ('categories', models.ManyToManyField(related_name='videos', to='category_app.category')),
                ('genres', models.ManyToManyField(related_name='videos', to='genre_app.genre')),
                ('thumbnail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail', to='video_app.imagemedia')),
                ('thumbnail_half', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail_half', to='video_app.imagemedia')),
                ('trailer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_trailer', to='video_app.audiovideomedia')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_media', to='video_app.audiovideomedia')),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
