# Generated by Django 5.2.5 on 2025-09-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
